import type { Product, Testimonial, GalleryItem } from './types';

export const products: Product[] = [
  // Birthday Cakes
  {
    id: 'bc-001',
    name: 'Classic Vanilla Dream',
    description: 'Light, fluffy vanilla sponge with silky buttercream frosting and fresh strawberries',
    price: 15000,
    image: '/images/products/vanilla-cake.jpg',
    category: 'birthday-cakes',
    isPopular: true,
  },
  {
    id: 'bc-002',
    name: 'Rich Chocolate Indulgence',
    description: 'Decadent triple chocolate layers with ganache and chocolate shavings',
    price: 18000,
    image: '/images/products/chocolate-cake.jpg',
    category: 'birthday-cakes',
    isPopular: true,
  },
  {
    id: 'bc-003',
    name: 'Red Velvet Royale',
    description: 'Classic red velvet with cream cheese frosting and white chocolate drizzle',
    price: 20000,
    image: '/images/products/red-velvet.jpg',
    category: 'birthday-cakes',
    isNew: true,
  },
  {
    id: 'bc-004',
    name: 'Fruit Paradise',
    description: 'Fresh seasonal fruits atop a light sponge with whipped cream',
    price: 22000,
    image: '/images/products/fruit-cake.jpg',
    category: 'birthday-cakes',
  },
  {
    id: 'bc-005',
    name: 'Caramel Delight',
    description: 'Salted caramel drip cake with caramelized nuts and butterscotch filling',
    price: 19000,
    image: '/images/products/caramel-cake.jpg',
    category: 'birthday-cakes',
    isNew: true,
  },

  // Wedding Cakes
  {
    id: 'wc-001',
    name: 'Elegant White Rose',
    description: '3-tier white fondant cake with handcrafted sugar roses and gold accents',
    price: 85000,
    image: '/images/products/wedding-white.jpg',
    category: 'wedding-cakes',
    isPopular: true,
  },
  {
    id: 'wc-002',
    name: 'Romantic Blush',
    description: 'Soft pink ombre buttercream with fresh flowers and pearl details',
    price: 75000,
    image: '/images/products/wedding-blush.jpg',
    category: 'wedding-cakes',
  },
  {
    id: 'wc-003',
    name: 'Classic Elegance',
    description: '4-tier royal icing masterpiece with intricate lace patterns',
    price: 120000,
    image: '/images/products/wedding-classic.jpg',
    category: 'wedding-cakes',
  },
  {
    id: 'wc-004',
    name: 'Modern Minimalist',
    description: 'Clean lines, geometric patterns, and metallic gold leaf accents',
    price: 95000,
    image: '/images/products/wedding-modern.jpg',
    category: 'wedding-cakes',
    isNew: true,
  },

  // Cupcakes
  {
    id: 'cp-001',
    name: 'Vanilla Bliss (6 pcs)',
    description: 'Classic vanilla cupcakes with swirled buttercream and sprinkles',
    price: 4500,
    image: '/images/products/cupcake-vanilla.jpg',
    category: 'cupcakes',
    isPopular: true,
  },
  {
    id: 'cp-002',
    name: 'Chocolate Heaven (6 pcs)',
    description: 'Rich chocolate cupcakes with chocolate ganache topping',
    price: 5000,
    image: '/images/products/cupcake-chocolate.jpg',
    category: 'cupcakes',
  },
  {
    id: 'cp-003',
    name: 'Red Velvet Love (6 pcs)',
    description: 'Red velvet cupcakes with cream cheese frosting hearts',
    price: 5500,
    image: '/images/products/cupcake-redvelvet.jpg',
    category: 'cupcakes',
    isNew: true,
  },
  {
    id: 'cp-004',
    name: 'Assorted Box (12 pcs)',
    description: 'A delightful mix of our best flavors - vanilla, chocolate, and strawberry',
    price: 9000,
    image: '/images/products/cupcake-assorted.jpg',
    category: 'cupcakes',
    isPopular: true,
  },

  // Pastries
  {
    id: 'ps-001',
    name: 'Meat Pie (6 pcs)',
    description: 'Flaky golden crust filled with seasoned minced meat and vegetables',
    price: 3000,
    image: '/images/products/meat-pie.jpg',
    category: 'pastries',
    isPopular: true,
  },
  {
    id: 'ps-002',
    name: 'Peanut Burger (10 pcs)',
    description: 'Crunchy Nigerian peanut burgers - perfect snack for any occasion',
    price: 2500,
    image: '/images/products/peanut-burger.jpg',
    category: 'pastries',
    isPopular: true,
  },
  {
    id: 'ps-003',
    name: 'Chin-chin (500g)',
    description: 'Crunchy, sweet Nigerian chin-chin - freshly made daily',
    price: 2000,
    image: '/images/products/chin-chin.jpg',
    category: 'pastries',
  },
  {
    id: 'ps-004',
    name: 'Small Chops Platter',
    description: 'Assorted spring rolls, samosa, puff-puff, and chicken bites for 20 guests',
    price: 15000,
    image: '/images/products/small-chops.jpg',
    category: 'pastries',
    isPopular: true,
  },
  {
    id: 'ps-005',
    name: 'Croissants (4 pcs)',
    description: 'Buttery, flaky French croissants - perfect for breakfast',
    price: 3500,
    image: '/images/products/croissants.jpg',
    category: 'pastries',
  },
  {
    id: 'ps-006',
    name: 'Donuts (6 pcs)',
    description: 'Soft, glazed ring donuts with your choice of topping',
    price: 3000,
    image: '/images/products/donuts.jpg',
    category: 'pastries',
    isNew: true,
  },

  // Specials
  {
    id: 'sp-001',
    name: 'Anniversary Special',
    description: 'Heart-shaped red velvet cake with gold leaf and fresh roses',
    price: 35000,
    image: '/images/products/anniversary.jpg',
    category: 'specials',
    isNew: true,
  },
  {
    id: 'sp-002',
    name: 'Corporate Gift Box',
    description: 'Premium selection of pastries and mini cakes for office celebrations',
    price: 25000,
    image: '/images/products/corporate-box.jpg',
    category: 'specials',
  },
  {
    id: 'sp-003',
    name: 'Kids Party Package',
    description: 'Character cake, 24 cupcakes, and small chops for 30 children',
    price: 45000,
    image: '/images/products/kids-party.jpg',
    category: 'specials',
    isPopular: true,
  },
];

export const testimonials: Testimonial[] = [
  {
    id: 't1',
    name: 'Adebola Johnson',
    occasion: 'Daughter\'s 10th Birthday',
    text: 'The unicorn cake O\'Rich made for my daughter was absolutely magical! Every child at the party couldn\'t stop talking about it. The taste was even better than it looked!',
    rating: 5,
    image: '/images/testimonials/customer1.jpg',
  },
  {
    id: 't2',
    name: 'Emeka & Chidinma Okafor',
    occasion: 'Wedding Reception',
    text: 'Our 5-tier wedding cake was the centerpiece of our reception. O\'Rich captured our vision perfectly. Fresh, delicious, and beautifully crafted. Thank you for making our day special!',
    rating: 5,
    image: '/images/testimonials/customer2.jpg',
  },
  {
    id: 't3',
    name: 'Fatima Ibrahim',
    occasion: 'Office Party',
    text: 'We ordered small chops and cupcakes for our office end-of-year party. Delivery was prompt, everything was fresh, and our colleagues loved it! Will definitely order again.',
    rating: 5,
    image: '/images/testimonials/customer3.jpg',
  },
  {
    id: 't4',
    name: 'Kunle Adeleke',
    occasion: 'Surprise Anniversary',
    text: 'Planned a surprise anniversary cake for my wife. O\'Rich not only delivered on time but the heart-shaped red velvet was the most delicious cake we\'ve ever had. She was in tears!',
    rating: 5,
    image: '/images/testimonials/customer4.jpg',
  },
  {
    id: 't5',
    name: 'Mrs. Folake Adesanya',
    occasion: 'Traditional Wedding',
    text: 'The traditional wedding cake with Ankara-inspired fondant design was breathtaking. Everyone asked where we got it. O\'Rich truly understands Nigerian celebrations!',
    rating: 5,
    image: '/images/testimonials/customer5.jpg',
  },
  {
    id: 't6',
    name: 'Dr. Olumide Peters',
    occasion: 'Graduation Celebration',
    text: 'Ordered a graduation cake for my daughter\'s medical school completion. The attention to detail - complete with a stethoscope design - was incredible. Highly recommend!',
    rating: 5,
    image: '/images/testimonials/customer6.jpg',
  },
  {
    id: 't7',
    name: 'Amaka Nwosu',
    occasion: 'Baby Shower',
    text: 'The baby shower cake and pastries were perfect! The pastel colors, the cute baby decorations, and most importantly, the amazing taste. My guests are still talking about it!',
    rating: 5,
    image: '/images/testimonials/customer7.jpg',
  },
  {
    id: 't8',
    name: 'Rasheed Mohammed',
    occasion: 'Corporate Event',
    text: 'We\'ve been using O\'Rich for all our corporate events. Their professionalism, consistency in quality, and ability to handle large orders makes them our go-to bakery in Ilorin.',
    rating: 5,
    image: '/images/testimonials/customer8.jpg',
  },
];

export const galleryItems: GalleryItem[] = [
  {
    id: 'g1',
    image: '/images/gallery/wedding-1.jpg',
    title: 'Royal White Wedding Cake',
    occasion: 'Traditional Wedding',
    feedback: 'The most beautiful cake we\'ve ever seen!',
  },
  {
    id: 'g2',
    image: '/images/gallery/birthday-1.jpg',
    title: 'Princess Castle Cake',
    occasion: '5th Birthday Party',
    feedback: 'My daughter felt like a real princess!',
  },
  {
    id: 'g3',
    image: '/images/gallery/cupcakes-1.jpg',
    title: 'Elegant Cupcake Tower',
    occasion: 'Engagement Party',
  },
  {
    id: 'g4',
    image: '/images/gallery/birthday-2.jpg',
    title: 'Football Theme Cake',
    occasion: 'Boy\'s 8th Birthday',
    feedback: 'Exactly what my son wanted!',
  },
  {
    id: 'g5',
    image: '/images/gallery/wedding-2.jpg',
    title: 'Blush Pink Wedding Cake',
    occasion: 'Garden Wedding',
  },
  {
    id: 'g6',
    image: '/images/gallery/pastries-1.jpg',
    title: 'Small Chops Spread',
    occasion: 'Corporate Launch Event',
    feedback: 'Professional and delicious!',
  },
  {
    id: 'g7',
    image: '/images/gallery/birthday-3.jpg',
    title: 'Floral Birthday Cake',
    occasion: '30th Birthday Celebration',
  },
  {
    id: 'g8',
    image: '/images/gallery/anniversary-1.jpg',
    title: 'Golden Anniversary Cake',
    occasion: '50th Wedding Anniversary',
    feedback: 'A masterpiece for our golden years!',
  },
  {
    id: 'g9',
    image: '/images/gallery/baby-1.jpg',
    title: 'Baby Shower Treats',
    occasion: 'Baby Shower',
  },
  {
    id: 'g10',
    image: '/images/gallery/graduation-1.jpg',
    title: 'Graduation Cap Cake',
    occasion: 'University Graduation',
    feedback: 'Perfect way to celebrate achievement!',
  },
  {
    id: 'g11',
    image: '/images/gallery/wedding-3.jpg',
    title: 'Naked Wedding Cake',
    occasion: 'Rustic Wedding',
  },
  {
    id: 'g12',
    image: '/images/gallery/birthday-4.jpg',
    title: 'Superhero Theme Cake',
    occasion: 'Twin Boys Birthday',
    feedback: 'Double the fun, double the delicious!',
  },
];

export const categories = [
  {
    id: 'birthday-cakes',
    name: 'Birthday Cakes',
    description: 'Make every birthday unforgettable',
    image: '/images/categories/birthday.jpg',
  },
  {
    id: 'wedding-cakes',
    name: 'Wedding Cakes',
    description: 'Elegant creations for your special day',
    image: '/images/categories/wedding.jpg',
  },
  {
    id: 'cupcakes',
    name: 'Cupcakes',
    description: 'Perfect little bites of happiness',
    image: '/images/categories/cupcakes.jpg',
  },
  {
    id: 'pastries',
    name: 'Pastries',
    description: 'Nigerian favorites baked fresh daily',
    image: '/images/categories/pastries.jpg',
  },
  {
    id: 'specials',
    name: 'Specials',
    description: 'Seasonal treats and custom packages',
    image: '/images/categories/specials.jpg',
  },
];

export const formatPrice = (price: number): string => {
  return new Intl.NumberFormat('en-NG', {
    style: 'currency',
    currency: 'NGN',
    minimumFractionDigits: 0,
  }).format(price);
};
